"use client";
// import type { Metadata } from "next";
import { Lora } from "next/font/google";
import Navbar from "./_component/Navbar";
import { ThemeProvider } from "next-themes";
import { useLenis } from "./_hooks/useLenis";
import Footer from "./_component/Footer";
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Next blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useLenis();
  return (
    <ThemeProvider attribute="class" defaultTheme="light" enableSystem={true}>
      <div className={`${lora.className}`}>
        <Navbar />
        {children}
        <Footer />
      </div>
    </ThemeProvider>
  );
}
